DaVitaLogin/DaVitaLogin/Models/ChangePasswordForm.cs
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class ChangePasswordForm
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string CurrentPassword { get; set; }

        [Required]
        public string NewPassword { get; set; }

        [Required]
        public string ConfirmPassword { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/ForgotPasswordChangeForm.cs
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class ForgotPasswordChangeForm
    {
        [Required]
        public string NewPassword { get; set; }

        [Required]
        public string ConfirmPassword { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/ForgotPasswordForm.cs
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class ForgotPasswordForm
    {
        [Required]
        public string Username { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/ForgotUsernameForm.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class ForgotUsernameForm
    {
        [Required]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? DateOfBirth { get; set; }

        [Required]
        public int LastFourSSN { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/LoginForm.cs
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class LoginForm
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/SecurityQuestion.cs
using System.ComponentModel.DataAnnotations;

namespace DaVitaLogin.Models
{
    public class SecurityQuestion
    {
        public string Question { get; set; }

        [Required]
        public string Answer { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Models/SecurityQuestionsForm.cs
namespace DaVitaLogin.Models
{
    public class SecurityQuestionsForm
    {
        public SecurityQuestion Question1 { get; set; }
        public SecurityQuestion Question2 { get; set; }
        public SecurityQuestion Question3 { get; set; }
    }
}

DaVitaLogin/DaVitaLogin/Controllers/ChangePasswordController.cs
using System.Web.Mvc;
using DaVitaLogin.Models;

namespace DaVitaLogin.Controllers
{
    public class ChangePasswordController : Controller
    {
        // GET: ChangePassword
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ChangePasswordForm model)
        {
            return View();
        }
    }
}

DaVitaLogin/DaVitaLogin/Controllers/ForgotPasswordController.cs
using System.Web.Mvc;
using DaVitaLogin.Models;

namespace DaVitaLogin.Controllers
{
    public class ForgotPasswordController : Controller
    {
        // GET: ForgotPassword
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ForgotPasswordForm model)
        {
            return View();
        }

        public ActionResult SecurityQuestions()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SecurityQuestions(SecurityQuestionsForm model)
        {
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ForgotPasswordChangeForm model)
        {
            return View();
        }
    }
}

DaVitaLogin/DaVitaLogin/Controllers/ForgotUsernameController.cs
using System.Web.Mvc;
using DaVitaLogin.Models;

namespace DaVitaLogin.Controllers
{
    public class ForgotUsernameController : Controller
    {
        // GET: ForgotUsername
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ForgotUsernameForm model)
        {
            return View();
        }
    }
}

DaVitaLogin/DaVitaLogin/Controllers/HomeController.cs
using System.Web.Mvc;
using DaVitaLogin.Models;

namespace DaVitaLogin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginForm model)
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }
    }
}

DaVitaLogin/DaVitaLogin/Views/Home/Help.cshtml
@{
    ViewBag.Title = "Help";
}

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <div class="col-md-10 center-block">
            <p>
                <a href="@Url.Action("Index","ForgotUsername")" class="btn btn-primary btn-lg full-width-button" role="button">Forgot Username</a>
            </p>
            <p>
                <a href="@Url.Action("Index", "ForgotPassword")" class="btn btn-primary btn-lg full-width-button" role="button">Forgot Password</a>
            </p>
            <p>
                <a href="@Url.Action("Index", "ChangePassword")" class="btn btn-primary btn-lg full-width-button" role="button">Change Password</a>
            </p>
            <p>
                <a href="@Url.Action("Index", "Home")" class="btn btn-default btn-lg full-width-button" role="button">Cancel</a>
            </p>
        </div>
    </div>
</div>

DaVitaLogin/DaVitaLogin/Views/Home/Index.cshtml
@model DaVitaLogin.Models.LoginForm

@{
    ViewBag.Title = "Login";
}

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <div class="col-md-10 center-block">
            <form class="login-form">
                <div class="inner-addon left-addon">
                    <i class="glyphicon glyphicon-user"></i>
                    @Html.TextBoxFor(x => x.Username, new {@class = "form-control login-top", @placeholder = "Username"})
                </div>
                <div class="inner-addon left-addon">
                    <i class="glyphicon glyphicon-lock"></i>
                    @Html.PasswordFor(x => x.Password, new {@class = "form-control login-bottom", @placeholder = "Password"})
                </div>
                <button type="button" class="btn btn-warning btn-lg full-width-button">Login</button>
                @Html.ValidationSummary()
            </form>
            <div class="text-center login-help">
                <a href="@Url.Action("Help", "Home")">Need help?</a>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaVitaLogin/DaVitaLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="container body-content">
    <header>
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <h1 class="logo">DaVita Village Login Service</h1>
            </div>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <p>Access to this site is limited to DaVita employees. The DaVita Intranet contains proprietary company information. Unauthorized entry may be a violation of state or federal law.</p>
                <p>&copy; 1997 - @DateTime.Now.Year Copyright DaVita Inc. All rights reserved. 2000 16th Street, Denver, CO 80202</p>
            </div>
        </div>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>